cadena=input("Ingresá un texto:")
print("El carácter en primer lugar es:", cadena[0]) 
print("Ingresá un número positivo menor a", len(cadena)) 
indice=int(input())
print("El carácter en esa posición es:", cadena[indice])